# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 782720cd8d3dd2983a9a996615e3b51a9fbdc9434a14bbb6cdaa75dc7b6c5f01b927c82c97584e4d388ec0fc834b075a9149fa3c2846eb7a234d452954aad4f6

test:
  secret_key_base: 04a8e4aeea52c9fdae3a07203ac73bd7e23f7b7f420a53448a656d58101065f589fa8f3295bedf0ae95351e50a72170000143c008f9169d1960cb4bac83d91c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
